apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
{{- toYaml .Values.command.args | nindent 12 }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.envFrom.configMap }}
            - secretRef:
                name: {{ .Values.envFrom.secret }}
          volumeMounts:
            - name: flohmarkt-data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: flohmarkt-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
