apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: flohmarkt
spec:
flohmarkt:
  replicas: {{ .Values.flohmarkt.replicaCount }}
  selector:
    matchLabels:
      app: flohmarkt
  template:
    metadata:
      labels:
        app: flohmarkt
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.flohmarkt.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.flohmarkt.image.pullPolicy }}
          args: ["web"]
          ports:
            - containerPort: {{ .Values.flohmarkt.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.flohmarkt.envFrom.configMap }}
            - secretRef:
                name: {{ .Values.flohmarkt.envFrom.secret }}
          volumeMounts:
            - name: flohmarkt-data
              mountPath: {{ .Values.flohmarkt.persistence.mountPath }}
      volumes:
        - name: flohmarkt-data
          persistentVolumeClaim:
            claimName: {{ .Values.flohmarkt.persistence.claimName }}
