apiVersion: apps/v1
kind: Deployment
metadata:
  name: flohmarkt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flohmarkt
  template:
    metadata:
      labels:
        app: flohmarkt
    spec:
      containers:
      
        - name: flohmarkt
          repository: harbor.obmondo.com/obmondo/flohmarkt
          tag: "1.0.0"
          command: ["flohmarkt", "web"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: flohmarkt-env
            - secretRef:
                name: flohmarkt-secrets
          volumeMounts:
            - name: flohmarkt-data
              mountPath: /var/lib/flohmarkt
      volumes:
        - name: flohmarkt-data
          persistentVolumeClaim:
            claimName: flohmarkt-data
