apiVersion: v2
appVersion: 1.3.1
description: A Helm chart for OpenSearch
maintainers:
- name: DandyDeveloper
- name: bbarani
- name: gaiksaya
- name: peterzhuamazon
- name: prudhvigodithi
- name: TheAlgo
name: opensearch
type: application
version: 1.10.0
