apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobilizon.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
  selector:
    app: mobilizon
