apiVersion: v2
appVersion: 1.22.3
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.5.20
- condition: postgresql-ha.enabled
  name: postgresql-ha
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.2.16
- condition: redis-cluster.enabled
  name: redis-cluster
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 10.3.0
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.6.4
description: Gitea Helm chart for Kubernetes
icon: https://gitea.com/assets/img/logo.svg
keywords:
- git
- issue tracker
- code review
- wiki
- gitea
- gogs
maintainers:
- email: charlie@charliedrage.com
  name: Charlie Drage
- email: maintainers@gitea.io
  name: Gitea Authors
- email: konrad.lother@novum-rgi.de
  name: Konrad Lother
- email: lucas.hahn@novum-rgi.de
  name: Lucas Hahn
- email: sk.bunsenbrenner@gmail.com
  name: Steven Kriegler
- email: patrick.schratz@gmail.com
  name: Patrick Schratz
name: gitea
sources:
- https://gitea.com/gitea/helm-chart
- https://github.com/go-gitea/gitea
- https://hub.docker.com/r/gitea/gitea/
type: application
version: 10.6.0
