apiVersion: v2
appVersion: v3.10.0-beta.2
description: A Helm chart for Gatekeeper
home: https://github.com/open-policy-agent/gatekeeper
keywords:
- open policy agent
name: gatekeeper
sources:
- https://github.com/open-policy-agent/gatekeeper.git
version: 3.10.0-beta.2
