apiVersion: v2
appVersion: 17.3.0
description: Teleport provides a secure SSH, Kubernetes, database and application
  remote access solution that doesn't get in the way.
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
- Teleport
name: teleport-kube-agent
version: 17.3.0
