apiVersion: v2
appVersion: 0.113.0
description: An opinionated installation of OTEL Collector for OpenObserve
maintainers:
- email: hello@openobserve.ai
  name: OpenObserve
  url: https://openobserve.ai
name: openobserve-collector
type: application
version: 0.3.18
