apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: {{ template "prometheus-linuxaid.namespace" . }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    {{- if .Values.prometheus.routePrefix }}
    match: Host(`{{ .Values.prometheus.server }}`) && PathPrefix(`{{ .Values.prometheus.routePrefix }}`)
    {{- else }}
    match: Host(`{{ .Values.prometheus.server }}`)
    {{- end }}
    priority: 10
    services:
    - kind: Service
      name: grafana-service
      namespace: {{ template "prometheus-linuxaid.namespace" . }}
      passHostHeader: true
      port: grafana
      nativeLB: true
    middlewares:
      - name: grafana-chain
        namespace: {{ template "prometheus-linuxaid.namespace" . }}
