apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: {{ template "prometheus-linuxaid.namespace" . }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    {{- if .Values.prometheus.routePrefix }}
    match: Host(`{{ .Values.prometheus.server }}`) && PathPrefix(`{{ .Values.prometheus.routePrefix }}`)
    {{- else }}
    match: Host(`{{ .Values.prometheus.server }}`)
    {{- end }}
    priority: 10
    services:
    - kind: Service
      name: prometheus-main
      namespace: {{ template "prometheus-linuxaid.namespace" . }}
      passHostHeader: true
      port: web
      nativeLB: true
  tls:
    options:
      name: prometheus-puppet-agent-tls-auth
      namespace: traefik
