apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: {{ .Values.controlPlane.instanceType }}
      sshKeyName: {{ .Values.controlPlane.sshKeyName }}
      imageLookupBaseOS: ubuntu-20.04
      publicIP: {{ .Values.controlPlane.publicIP }}
      ami: {{ toYaml .Values.controlPlane.ami | nindent 8 }}
      rootVolume:
        size: {{ .Values.controlPlane.rootVolumeSize | default 35 }}

{{- if (not (.Values.global.capa).autoScaler) }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-md-0
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: {{ .Values.workerNodes.instanceType }}
      sshKeyName: {{ .Values.workerNodes.sshKeyName }}
      imageLookupBaseOS: ubuntu-20.04
      publicIP: {{ .Values.workerNodes.publicIP }}
      ami: {{ toYaml .Values.workerNodes.ami | nindent 8 }}
      rootVolume:
        size: {{ .Values.workerNodes.rootVolumeSize | default 35 }}
{{- end }}
