apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: {{ .Values.controlPlane.instanceType }}
      sshKeyName: {{ .Values.controlPlane.sshKeyName }}
      imageLookupBaseOS: ubuntu-20.04
      publicIP: {{ .Values.controlPlane.publicIP }}
      ami: {{ toYaml .Values.controlPlane.ami | nindent 8 }}
      rootVolume:
        size: {{ .Values.controlPlane.rootVolumeSize | default 35 }}

{{- if (.Values.global).enableClusterAutoscaler }}
{{- range $index, $nodeGroup := $.Values.nodeGroups }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ printf "%s-%s" $.Values.global.clusterName $nodeGroup.name }}
spec:
  template:
    spec:
      ami: {{ toYaml $nodeGroup.ami | nindent 8 }}
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: {{ $nodeGroup.instanceType }}
      sshKeyName: {{ $nodeGroup.sshKeyName }}
      imageLookupBaseOS: ubuntu-20.04
      rootVolume:
        size: {{ $nodeGroup.rootVolumeSize | default 35 }}
{{- end }}
{{- end }}
