image:
  repository: honestica/kube-iptables-tailer
  tag: master-56
  pullPolicy: IfNotPresent

# Specify to use specific priorityClass for pods
# ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
# If a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority
# Pods to make scheduling of the pending Pod possible.
priorityClassName: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

updateStrategy:
  type: RollingUpdate

# Only one of the next configuration should be enabled
# iptablesLogPath: "/var/log/iptables.log"

# If using EKS uncomment this line
# journalDirectory: "/var/log/journal"

iptablesLogPrefix: "calico-packet:"
kubeApiServicer: "https://kubernetes.default:443"

podAnnotations: {}
  # prometheus.io/scrape: "true"
  # prometheus.io/port: "9090"

rbac:
  create: true
  pspEnabled: true

serviceAccount:
  create: true
  name:

# Should alway enabled or you have to do manual iptable configuration on each host
calico:
  loggingEnable: true
  # check your apiversion with `kubectl api-versions`
  apiVersion: projectcalico.org/v3

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraArgs: []

syslogSidecar:
  enabled: false
  image: rsyslog/syslog_appliance_alpine
  tag: latest

# extraVolumes and extraVolumeMounts allows you to mount other volumes
extraVolumes: []
#  - name: service-logs
#    emptyDir: {}
extraVolumeMounts: []
#  - name: service-logs
#    mountPath: /my-service-logs
