{{- if .Values.serviceAccount.create -}}
{{- $chart := "mail" -}}
{{- $labels := include (print $chart ".labels") . -}}
{{- $serviceAccountName := include (print $chart ".serviceAccountName") . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  labels:
    {{- $labels | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}{{ toYaml . | nindent 4 }}{{ end }}
{{- end }}
