apiVersion: v2
appVersion: 4.3.8
dependencies:
- name: elasticsearch
  repository: https://helm.elastic.co
  tags:
  - install-elasticsearch
  version: 7.16.2
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  tags:
  - install-mongodb
  version: 10.31.2
description: Graylog is the centralized log management solution built to open standards
  for capturing, storing, and enabling real-time analysis of terabytes of machine
  data.
home: https://www.graylog.org
icon: https://global-uploads.webflow.com/5a218ef7897bf400019e2f16/5a218ef7897bf400019e2f60_logo-graylog.png
keywords:
- graylog
- logs
- syslog
- gelf
maintainers:
- email: goonohc@gmail.com
  name: KongZ
name: graylog
sources:
- https://github.com/KongZ/charts
version: 2.2.0
