apiVersion: v2
appVersion: 6.3.1
dependencies:
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  tags:
  - install-mongodb
  version: 16.5.21
- name: opensearch
  repository: https://opensearch-project.github.io/helm-charts
  tags:
  - install-opensearch
  version: 2.34.0
description: Graylog is the centralized log management solution built to open standards
  for capturing, storing, and enabling real-time analysis of terabytes of machine
  data.
home: https://www.graylog.org
icon: https://global-uploads.webflow.com/5a218ef7897bf400019e2f16/5a218ef7897bf400019e2f60_logo-graylog.png
keywords:
- graylog
- logs
- syslog
- gelf
maintainers:
- email: goonohc@gmail.com
  name: KongZ
- email: lj@luizjr.dev
  name: LuizJr
  url: https://luizjr.dev
name: graylog
sources:
- https://github.com/KongZ/charts
type: application
version: 2.3.17
