apiVersion: v2
appVersion: 10.5.1
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: https://charts.helm.sh/stable
  version: 1.6.4
description: Mattermost Team Edition server.
home: https://mattermost.com
icon: http://www.mattermost.org/wp-content/uploads/2016/04/icon.png
keywords:
- mattermost
- communication
- team collaboration
name: mattermost-team-edition
sources:
- https://github.com/mattermost/mattermost-server
- https://github.com/mattermost/mattermost-helm
type: application
version: 6.6.71
