apiVersion: v2
appVersion: 0.9.4
description: A Helm chart for Cerebro - a web admin tool to manage ElasticSearch
home: https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/cerebro
icon: https://raw.githubusercontent.com/lmenezes/cerebro/main/public/img/logo.png
keywords:
- cerebro
- elasticsearch
- admin
maintainers:
- email: cdesaintmartin@wiremind.io
  name: desaintmartin
- email: amrini@wiremind.io
  name: machine424
- email: fminaud@wiremind.io
  name: francoisminaud
name: cerebro
sources:
- https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/cerebro
- https://github.com/lmenezes/cerebro-docker
version: 2.0.2
