annotations:
  artifacthub.io/changes: |
    - Update base image to 2.5.5 release
    - Add PullSecret for default backend
    - Add extraEnvs to the main container
apiVersion: v2
appVersion: 2.5.5
description: A Helm chart for HAProxy on Kubernetes
home: https://github.com/haproxytech/helm-charts/tree/main/haproxy
icon: https://raw.githubusercontent.com/haproxytech/helm-charts/main/haproxy/chart-icon.png
keywords:
- haproxy
kubeVersion: '>=1.17.0-0'
maintainers:
- email: dkorunic@haproxy.com
  name: Dinko Korunic
name: haproxy
sources:
- http://www.haproxy.org/
type: application
version: 1.14.0
