apiVersion: v1
kind: Service
metadata:
  name: {{ include "vuls-dictionary.fullname" . }}
  labels:
    {{- include "vuls-dictionary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.goCVEDictionary }}
      targetPort: http-go-cve
      protocol: TCP
      name: http-go-cve
    - port: {{ .Values.service.govalDictionary }}
      targetPort: http-goval
      protocol: TCP
      name: http-goval
  selector:
    {{- include "vuls-dictionary.selectorLabels" . | nindent 4 }}
