apiVersion: v2
appVersion: v7.3.0-bookworm
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.7.27
- condition: valkey.enabled
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.4.7
description: A Helm chart for deploying PeerTube on Kubernetes
maintainers:
- name: cloudymax
  url: https://github.com/cloudymax
- name: JesseBot
  url: https://github.com/jessebot
name: peertube
type: application
version: 0.8.0
