apiVersion: v2
name: kube-prometheus-stack
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 30.0.0
    repository: https://prometheus-community.github.io/helm-charts
    #repository: "oci://ghcr.io/Obmondo"
    # see versions here: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
