apiVersion: v2
appVersion: v0.14.0
description: A Helm chart for Kubernetes
home: https://github.com/prometheus-community/smartctl_exporter
maintainers:
- name: kfox1111
  url: https://github.com/kfox1111
- email: rootsandtrees@posteo.de
  name: zeritti
  url: https://github.com/zeritti
name: prometheus-smartctl-exporter
sources:
- https://github.com/prometheus-community/smartctl_exporter
type: application
version: 0.15.4
