{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.rbac.serviceAccountAnnotations }}
  annotations:
    {{- range $key, $value := .Values.rbac.serviceAccountAnnotations }}
    {{   $key }}: {{ tpl ($value) $ | quote }}
    {{- end }}
  {{- end}}
  name: {{ include "gitlab-runner.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.rbac.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.rbac.imagePullSecrets }}
  - name: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end -}}
