# Added features outside upstream chart
middleware:
  jwt:
    enabled: false
    headers:
      X-Subject: sub
      # public_key: |
      #   -----BEGIN PUBLIC KEY-----
      #   Asdads
      #   -----END PUBLIC KEY-----
traefik:
  instanceLabelOverride: traefik
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  # NOTE: this is to disable the anonymous usage reporting - https://doc.traefik.io/traefik/contributing/data-collection/
  globalArguments: []
  deployment:
    replicas: 2
    revisionHistoryLimit: "0"
  logs:
    access:
      enabled: true
  ports:
    web:
      redirectTo:
        port: websecure
    websecure:
      tls:
        enabled: true

  additionalArguments:
    - "--entrypoints.web.proxyprotocol=true"
    - "--entrypoints.web.proxyprotocol.insecure=true"
    - "--entrypoints.websecure.proxyprotocol=true"
    - "--entrypoints.websecure.proxyprotocol.insecure=true"
  # https://github.com/argoproj/argo-cd/issues/1704#issuecomment-904741817
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true

  metrics:
    prometheus:
      serviceMonitor:
        metricRelabelings: []
        relabelings: []
        jobLabel: traefik
        interval: 10s
        honorLabels: true

# defines an ingressroute (public url - custom traefik CRD that replaces generic ingress type) for traefik dashboard. Not advised to enable - and below needs addition of a specific url to be accessible.
#  ingressRoute:
#    dashboard:
#      enabled: true
#      annotations:
#        traefik.ingress.kubernetes.io/router.tls: "true"
#        cert-manager.io/cluster-issuer: letsencrypt
