apiVersion: v2
name: prometheus-adapter
version: 1.0.0
dependencies:
  - name: prometheus-adapter
    version: 2.12.1
    #repository: https://prometheus-community.github.io/helm-charts
    repository: "oci://ghcr.io/Obmondo"
