apiVersion: v2
appVersion: v1.1.22
dependencies:
- condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.8.0
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 11.0.10
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.9.10
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 10.3.9
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.13.2
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.29.6
- condition: ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.1.4
description: Developer-friendly incident response with brilliant Slack integration
name: oncall
type: application
version: 1.1.22
