apiVersion: v2
appVersion: 17.0.1-legacy
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.16.2
description: Open Source Identity and Access Management For Modern Applications and Services
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
keywords:
- sso
- idm
- openid connect
- saml
- kerberos
- ldap
maintainers:
- email: unguiculus@gmail.com
  name: unguiculus
- email: thomas.darimont+github@gmail.com
  name: thomasdarimont
name: keycloak
sources:
- https://github.com/codecentric/helm-charts
- https://github.com/jboss-dockerfiles/keycloak
- https://github.com/bitnami/charts/tree/master/bitnami/postgresql
version: 18.4.0
