apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ .Values.global.clusterName}}-systempool
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.global.clusterName }}
  replicas: {{ .Values.systemPool.replicas }}
  template:
    spec:
      clusterName: {{ .Values.global.clusterName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: mspool01
        namespace: {{ .Release.Namespace }}
      version: {{ .Values.global.kubernetes.version }}
      bootstrap:
        dataSecretName: {{ .Values.global.clientSecret}}
