{{- if .Values.managedCluster }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: mupool01
spec:
  mode: User
  osDiskSizeGB: {{ .Values.userPool.osDiskSizeGB }}
  sku: {{ .Values.userPool.sku }}
{{- end }}