apiVersion: v2
appVersion: 20241023.232054.09438bd
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.6
description: Yetibot and its Postgresql dependency packaged as a Helm Chart
home: https://github.com/yetibot/yetibot-helm
icon: https://yetibot.com/img/yetibot_logo.svg
maintainers:
- name: devth
  url: https://devth.com
name: yetibot
type: application
version: 1.0.107
