apiVersion: v2
appVersion: 16.1.0
dependencies:
- alias: operator
  name: teleport-operator
  repository: ""
  version: 16.1.0
description: Teleport is an access platform for your infrastructure
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
- Teleport
name: teleport-cluster
version: 16.1.0
