apiVersion: v2
appVersion: 8.1.5
description: Teleport is a unified access plane for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
- Teleport
name: teleport-cluster
version: 8.1.5
