apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flohmarkt
spec:
  rules:
    - host: flohmarkt.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flohmarkt
                port:
                  number: 80
